name: Publish Nuget by Tag

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'readme.md'
  pull_request:

jobs:
  CheckSkipCI:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.pull_request.title, '[skip-ci]')
    steps:
      - run: exit 0

  build:
    runs-on: windows-latest
    needs: [CheckSkipCI]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Version
      uses: aarnott/nbgv@v0.4.0
      with:
        setAllVars: true

    - name: Pack
      run: dotnet pack --configuration Release --output build/packages

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: |
          if ( "${{github.ref}}" -match "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push build\packages\**\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.AURA_UI_KEY}}
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
